services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=database
      - DB_NAME=cars_db
      - DB_USER=root

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 8501:8501

  database:
    #defines the mysql version
    image: mysql:8.0
    environment:
    #defines the required root password as my .env
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=cars_db
    #gives the necessary ports so the db can communicate
    ports:
      - 3306:3306
    volumes:
    #creates a volume where new data/changes will be saved
      - db_data:/var/lib/mysql

volumes:
#creates the volume to be used later
  db_data: